[package]
name = "bm_http"
description = "HTTP endpoints for boilmaster."
version = "0.0.0"
publish = false

edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bm_asset = { path = "../bm_asset_fs" }
bm_data = { path = "../bm_data_fs" }
bm_read = { path = "../bm_read" }
bm_schema = { path = "../bm_schema" }
bm_search = { path = "../bm_search" }
bm_version = { path = "../bm_version" }

aho-corasick.workspace = true
anyhow.workspace = true
aide = { workspace = true, features = [
  "axum",
  "axum-json",
  "axum-query",
  "axum-extra-headers",
  "macros",
] }
axum = { workspace = true, features = ["macros"] }
axum-extra = { workspace = true, features = ["typed-header"] }
either.workspace = true
git-version.workspace = true
ironworks = { workspace = true }
ironworks_schema.workspace = true
maud = { workspace = true, features = ["axum"] }
mime.workspace = true
nom.workspace = true
regex.workspace = true
schemars = { workspace = true, features = ["preserve_order", "uuid1"] }
seahash.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true }
tokio-util.workspace = true
tower-http = { workspace = true, features = ["cors", "fs", "trace"] }
tracing.workspace = true
uuid = { workspace = true, features = ["serde"] }
reqwest = { workspace = true, features = ["json", "stream"] }
sha2.workspace = true
subtle = "2.6"
percent-encoding = "2.3"
tempfile = "3.19.1"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }
tower = { version = "0.5", features = ["util"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
bm_asset_index = { path = "../bm_asset_index" }
bytes.workspace = true
crc32fast.workspace = true
image = { workspace = true, features = ["webp", "png", "jpeg"] }
object_store.workspace = true
tower = { version = "0.5", features = ["util"] }
