[tracing.console]
enabled = false

[tracing.stdout]
enabled = true
format = "full"
filters.default = "debug"
filters.hyper = "info"

[http]
# address = "0.0.0.0"
port = 8080
directory = "static"

[http.admin.auth]
username = "username"
password = "password"

[http.api1.asset]
maxage = 604800 # 1 week

[http.api1.search]
limit.default = 100
limit.max = 500
limit.depth = 2
fields.exdschema = "Name,Singular,Icon"
transient.exdschema = ""

[http.api1.sheet]
limit.default = 100
limit.max = 500
limit.depth = 2
list.fields.exdschema = "Name,Singular,Icon"
list.transient.exdschema = ""
entry.fields.exdschema = "*"
entry.transient.exdschema = "*"

[read.language]
default = "chs"
# This default configuration is set up for the global game client, which does not ship Chinese or Korean data.
exclude = []

[game]
# Downloaded ixion releases; keep this directory writable and persistent.
directory = "game"

[schema]
default = "exdschema"
interval = 3600       # 1 hour

[schema.exdschema]
default = "2:ver:request"
remote = "https://github.com/xivdev/EXDSchema.git"
directory = "exdschema"

[search.sqlite]
directory = "search"

[search.sqlite.cursor]
ttl = 3600 # 1 hour
tti = 300  # 5 minutes
